version: '3.4'

services:
    stub:
        build:
            context: ./application/
        ports:
            - 8003:8080
        environment:
            NEW_RELIC_LICENSE_KEY: $NEW_RELIC_LICENSE_KEY
