version: '3.4'

services:
    stub:
        build:
            context: ./stub/
        ports:
            - 8003:8080

    app:
        build:
            context: ./application
        ports:
            - 8002:80
        volumes:
            - ./application/:/var/www/html:cached
        depends_on:
            - couchbase.one
            - couchbase.two
            - couchbase.three
        env_file:
            - .env

    varnish:
        image: mio101/varnish-ncsa
        volumes:
            - ./varnish/default.vcl:/etc/varnish/default.vcl
        ports:
            - "8001:80"
        depends_on:
            - stub
        environment:
            VARNISH_PORT: 80
            VARNISHNCSA: "true"

    couchbase:
        image: couchbase/server:community-5.1.1
        ports:
            - 8091:8091

    couchbase.two:
        image: couchbase/server:community-5.1.1
        ports:
            - 8092:8091

    couchbase.three:
        image: couchbase/server:community-5.1.1
        ports:
            - 8093:8091
