version: '3.4'

services:
    stub: # Go (just for fun)
        build:
            context: ./stub/
        ports:
            - 8003:8080

    app: # PHP
        build:
            context: ./application
        ports:
            - 8002:80
        volumes:
            - ./application/:/var/www/html:cached
        depends_on:
            - couchbase.1
            - couchbase.2
            - couchbase.3
            - redis.1
        env_file:
            - .env

    varnish:
        # https://www.datadoghq.com/blog/top-varnish-performance-metrics/

        # https://github.com/MioYvo/docker-varnish because it has various log output options available
        image: mio101/varnish-ncsa
        volumes:
            - ./varnish/default.vcl:/etc/varnish/default.vcl
        ports:
            - "8001:80"
        depends_on:
            - stub
        environment:
            VARNISH_PORT: 80
            VARNISHNCSA: "true"
            # https://varnish-cache.org/docs/trunk/reference/varnishncsa.html#format
            VARNISHNCSA_FORMAT: "'%{Host}i %h %l %u %t \"%r\" %s %b %D \"%{Referer}i\" \"%{Varnish:hitmiss}x\"'"

            # https://varnish-cache.org/docs/trunk/users-guide/storage-backends.html#malloc
            # https://stackoverflow.com/questions/8016643/what-happens-when-varnish-cache-is-full
            # https://info.varnish-software.com/blog/understanding-varnish-cache-memory-usage
            VARNISH_RAM_STORAGE: "50M"
    
    redis.1:
        image: redis:alpine

    couchbase.1:
        image: couchbase/server:community-5.1.1
        ports:
            - 8091:8091

    couchbase.2:
        image: couchbase/server:community-5.1.1
        ports:
            - 8092:8091

    couchbase.3:
        image: couchbase/server:community-5.1.1
        ports:
            - 8093:8091
